--- 
language: php

php:
  - 5.3

notifications:
  campfire:
    rooms:
      secure: Cn+Vouj2Mg6hcvg1iR/zGM8iOhBWksAwQVKcUR1e/7kYTduNfMTI8miaMDIyDHsafibrvf/5QxvL7H0yU+tQUJ7HZID359z3VXpuA3PTno7BdwbvlklKyRBmjn+/6vAG9g/5wT56QKSBnxaUo4Qxv4q1naFdf3o8wM22MtiB0Ck=

script:
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - mkdir -p build/logs
  - composer require --dev satooshi/php-coveralls:dev-master
  - composer install
  - mysql -e 'create database `test-services-manager`;'
  - mysql --default-character-set=utf8 test-services-manager < tests/test_data/structure.sql

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
